### ISSUE TITLE
Workflow diagram issues 

### ISSUE THREAD

**Issue by lsnovich** [elagrog/Hamburger-API-Final-Project#19]
There are a few items you need to look at with the diagram:
1. You should eliminate the choices and just have it show the workflow steps (the big picture items)
   - Order burger meal
   - Choose patty type
   - Choose weight
   - Choose quantity
   etc. 
2. Your lines need to be straighter and the design simplified.
3. Try to keep it to 10 items or less

**Comment by elagrog** [comment]
I have redone this diagram.
