### ISSUE TITLE
diagram issues

### ISSUE THREAD

**Issue by lsnovich** [elagrog/Hamburger-API-Final-Project#34]
The diagram needs some changes
1. Usually a diamond is a decision point which is a yes / no question
    for example - want sides?
    and then the yes arrow points to a rectangle which says Order side(s) and then loops back to the next step. The No arrow goes to the next step directly.  You need to do this for each decision point - so choose carefully.
    2. One of your decision points is repeated 2x.

**Comment by elagrog** [comment]
I think I have fixed it.
