### ISSUE TITLE
logic confliction in your properties table for post

### ISSUE THREAD

**Issue by lsnovich** [elagrog/Hamburger-API-Final-Project#35]
when you have a property which can be repeated, the better way to do this is
1. list it ONCE
2. list all available options
3. explain that the option can be repeated n amount of times, where n is the maximum number
4. explain that none or 0 is an option (if it is)
and that is all
I should not see that
topping1 choices are pickles and tomatoes and topping 2 choices are onion and cheese (for example) - I should be able to order from the same set of choices each time.  You can explain that once selected the choice is no longer available for the second choice. 
also, you can say that "extra x" is available by choosing the same topping twice.

**Comment by elagrog** [comment]
I think it makes perfect sense but I've delete all the toppings and all the options, except for one.. Now some red font is appearing and I can't work on this anymore.

**Comment by elagrog** [comment]
Laura, I think I fixed it. I even had some problem in the code, which I was then able to fix in a code app, thanks to the coding class that I'm taking!

**Comment by elagrog** [comment]
Laura, I think I fixed it. I even had some problem in the code, which I was then able to fix in a code app, thanks to the coding class that I'm taking! @lsnovich

**Comment by lsnovich** [comment]
the easier way to fix this is to list the issue in the PR that fixes it. 
But now it's done you can close the issue.
